language: go
go: tip
script: go get code.google.com/p/go.tools/cmd/vet && go get github.com/cloudflare/redoctober && go test github.com/cloudflare/redoctober... && go vet github.com/cloudflare/redoctober...
notifications:
  email:
    recipients:
      - albert@cloudflare.com
      - nick@cloudflare.com
      - dane@cloudflare.com
    on_success: never
    on_failure: change
